//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperHero.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cours()
        {
            this.CourseCharacters = new HashSet<CourseCharacter>();
        }
    
        public int CourseID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int CourseTypeID { get; set; }
        public System.DateTime Date { get; set; }
        public int LocationID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseCharacter> CourseCharacters { get; set; }
        public virtual CourseType CourseType { get; set; }
        public virtual Location Location { get; set; }
    }
}
